// Code generated by protoc-gen-go.
// source: gcsdk_gcmessages.proto
// DO NOT EDIT!

package csgobufs

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GCConnectionStatus int32

const (
	GCConnectionStatus_GCConnectionStatus_HAVE_SESSION              GCConnectionStatus = 0
	GCConnectionStatus_GCConnectionStatus_GC_GOING_DOWN             GCConnectionStatus = 1
	GCConnectionStatus_GCConnectionStatus_NO_SESSION                GCConnectionStatus = 2
	GCConnectionStatus_GCConnectionStatus_NO_SESSION_IN_LOGON_QUEUE GCConnectionStatus = 3
	GCConnectionStatus_GCConnectionStatus_NO_STEAM                  GCConnectionStatus = 4
)

var GCConnectionStatus_name = map[int32]string{
	0: "GCConnectionStatus_HAVE_SESSION",
	1: "GCConnectionStatus_GC_GOING_DOWN",
	2: "GCConnectionStatus_NO_SESSION",
	3: "GCConnectionStatus_NO_SESSION_IN_LOGON_QUEUE",
	4: "GCConnectionStatus_NO_STEAM",
}
var GCConnectionStatus_value = map[string]int32{
	"GCConnectionStatus_HAVE_SESSION":              0,
	"GCConnectionStatus_GC_GOING_DOWN":             1,
	"GCConnectionStatus_NO_SESSION":                2,
	"GCConnectionStatus_NO_SESSION_IN_LOGON_QUEUE": 3,
	"GCConnectionStatus_NO_STEAM":                  4,
}

func (x GCConnectionStatus) Enum() *GCConnectionStatus {
	p := new(GCConnectionStatus)
	*p = x
	return p
}
func (x GCConnectionStatus) String() string {
	return proto.EnumName(GCConnectionStatus_name, int32(x))
}
func (x *GCConnectionStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GCConnectionStatus_value, data, "GCConnectionStatus")
	if err != nil {
		return err
	}
	*x = GCConnectionStatus(value)
	return nil
}
func (GCConnectionStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

type CMsgSOIDOwner struct {
	Type             *uint32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Id               *uint64 `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgSOIDOwner) Reset()                    { *m = CMsgSOIDOwner{} }
func (m *CMsgSOIDOwner) String() string            { return proto.CompactTextString(m) }
func (*CMsgSOIDOwner) ProtoMessage()               {}
func (*CMsgSOIDOwner) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *CMsgSOIDOwner) GetType() uint32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *CMsgSOIDOwner) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type CMsgSOSingleObject struct {
	TypeId           *int32         `protobuf:"varint,2,opt,name=type_id" json:"type_id,omitempty"`
	ObjectData       []byte         `protobuf:"bytes,3,opt,name=object_data" json:"object_data,omitempty"`
	Version          *uint64        `protobuf:"fixed64,4,opt,name=version" json:"version,omitempty"`
	OwnerSoid        *CMsgSOIDOwner `protobuf:"bytes,5,opt,name=owner_soid" json:"owner_soid,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *CMsgSOSingleObject) Reset()                    { *m = CMsgSOSingleObject{} }
func (m *CMsgSOSingleObject) String() string            { return proto.CompactTextString(m) }
func (*CMsgSOSingleObject) ProtoMessage()               {}
func (*CMsgSOSingleObject) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *CMsgSOSingleObject) GetTypeId() int32 {
	if m != nil && m.TypeId != nil {
		return *m.TypeId
	}
	return 0
}

func (m *CMsgSOSingleObject) GetObjectData() []byte {
	if m != nil {
		return m.ObjectData
	}
	return nil
}

func (m *CMsgSOSingleObject) GetVersion() uint64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *CMsgSOSingleObject) GetOwnerSoid() *CMsgSOIDOwner {
	if m != nil {
		return m.OwnerSoid
	}
	return nil
}

type CMsgSOMultipleObjects struct {
	ObjectsModified  []*CMsgSOMultipleObjects_SingleObject `protobuf:"bytes,2,rep,name=objects_modified" json:"objects_modified,omitempty"`
	Version          *uint64                               `protobuf:"fixed64,3,opt,name=version" json:"version,omitempty"`
	ObjectsAdded     []*CMsgSOMultipleObjects_SingleObject `protobuf:"bytes,4,rep,name=objects_added" json:"objects_added,omitempty"`
	ObjectsRemoved   []*CMsgSOMultipleObjects_SingleObject `protobuf:"bytes,5,rep,name=objects_removed" json:"objects_removed,omitempty"`
	OwnerSoid        *CMsgSOIDOwner                        `protobuf:"bytes,6,opt,name=owner_soid" json:"owner_soid,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (m *CMsgSOMultipleObjects) Reset()                    { *m = CMsgSOMultipleObjects{} }
func (m *CMsgSOMultipleObjects) String() string            { return proto.CompactTextString(m) }
func (*CMsgSOMultipleObjects) ProtoMessage()               {}
func (*CMsgSOMultipleObjects) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *CMsgSOMultipleObjects) GetObjectsModified() []*CMsgSOMultipleObjects_SingleObject {
	if m != nil {
		return m.ObjectsModified
	}
	return nil
}

func (m *CMsgSOMultipleObjects) GetVersion() uint64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *CMsgSOMultipleObjects) GetObjectsAdded() []*CMsgSOMultipleObjects_SingleObject {
	if m != nil {
		return m.ObjectsAdded
	}
	return nil
}

func (m *CMsgSOMultipleObjects) GetObjectsRemoved() []*CMsgSOMultipleObjects_SingleObject {
	if m != nil {
		return m.ObjectsRemoved
	}
	return nil
}

func (m *CMsgSOMultipleObjects) GetOwnerSoid() *CMsgSOIDOwner {
	if m != nil {
		return m.OwnerSoid
	}
	return nil
}

type CMsgSOMultipleObjects_SingleObject struct {
	TypeId           *int32 `protobuf:"varint,1,opt,name=type_id" json:"type_id,omitempty"`
	ObjectData       []byte `protobuf:"bytes,2,opt,name=object_data" json:"object_data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CMsgSOMultipleObjects_SingleObject) Reset()         { *m = CMsgSOMultipleObjects_SingleObject{} }
func (m *CMsgSOMultipleObjects_SingleObject) String() string { return proto.CompactTextString(m) }
func (*CMsgSOMultipleObjects_SingleObject) ProtoMessage()    {}
func (*CMsgSOMultipleObjects_SingleObject) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{2, 0}
}

func (m *CMsgSOMultipleObjects_SingleObject) GetTypeId() int32 {
	if m != nil && m.TypeId != nil {
		return *m.TypeId
	}
	return 0
}

func (m *CMsgSOMultipleObjects_SingleObject) GetObjectData() []byte {
	if m != nil {
		return m.ObjectData
	}
	return nil
}

type CMsgSOCacheSubscribed struct {
	Objects          []*CMsgSOCacheSubscribed_SubscribedType `protobuf:"bytes,2,rep,name=objects" json:"objects,omitempty"`
	Version          *uint64                                 `protobuf:"fixed64,3,opt,name=version" json:"version,omitempty"`
	OwnerSoid        *CMsgSOIDOwner                          `protobuf:"bytes,4,opt,name=owner_soid" json:"owner_soid,omitempty"`
	XXX_unrecognized []byte                                  `json:"-"`
}

func (m *CMsgSOCacheSubscribed) Reset()                    { *m = CMsgSOCacheSubscribed{} }
func (m *CMsgSOCacheSubscribed) String() string            { return proto.CompactTextString(m) }
func (*CMsgSOCacheSubscribed) ProtoMessage()               {}
func (*CMsgSOCacheSubscribed) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *CMsgSOCacheSubscribed) GetObjects() []*CMsgSOCacheSubscribed_SubscribedType {
	if m != nil {
		return m.Objects
	}
	return nil
}

func (m *CMsgSOCacheSubscribed) GetVersion() uint64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *CMsgSOCacheSubscribed) GetOwnerSoid() *CMsgSOIDOwner {
	if m != nil {
		return m.OwnerSoid
	}
	return nil
}

type CMsgSOCacheSubscribed_SubscribedType struct {
	TypeId           *int32   `protobuf:"varint,1,opt,name=type_id" json:"type_id,omitempty"`
	ObjectData       [][]byte `protobuf:"bytes,2,rep,name=object_data" json:"object_data,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CMsgSOCacheSubscribed_SubscribedType) Reset()         { *m = CMsgSOCacheSubscribed_SubscribedType{} }
func (m *CMsgSOCacheSubscribed_SubscribedType) String() string { return proto.CompactTextString(m) }
func (*CMsgSOCacheSubscribed_SubscribedType) ProtoMessage()    {}
func (*CMsgSOCacheSubscribed_SubscribedType) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{3, 0}
}

func (m *CMsgSOCacheSubscribed_SubscribedType) GetTypeId() int32 {
	if m != nil && m.TypeId != nil {
		return *m.TypeId
	}
	return 0
}

func (m *CMsgSOCacheSubscribed_SubscribedType) GetObjectData() [][]byte {
	if m != nil {
		return m.ObjectData
	}
	return nil
}

type CMsgSOCacheUnsubscribed struct {
	OwnerSoid        *CMsgSOIDOwner `protobuf:"bytes,2,opt,name=owner_soid" json:"owner_soid,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *CMsgSOCacheUnsubscribed) Reset()                    { *m = CMsgSOCacheUnsubscribed{} }
func (m *CMsgSOCacheUnsubscribed) String() string            { return proto.CompactTextString(m) }
func (*CMsgSOCacheUnsubscribed) ProtoMessage()               {}
func (*CMsgSOCacheUnsubscribed) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *CMsgSOCacheUnsubscribed) GetOwnerSoid() *CMsgSOIDOwner {
	if m != nil {
		return m.OwnerSoid
	}
	return nil
}

type CMsgSOCacheSubscriptionCheck struct {
	Version          *uint64        `protobuf:"fixed64,2,opt,name=version" json:"version,omitempty"`
	OwnerSoid        *CMsgSOIDOwner `protobuf:"bytes,3,opt,name=owner_soid" json:"owner_soid,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *CMsgSOCacheSubscriptionCheck) Reset()                    { *m = CMsgSOCacheSubscriptionCheck{} }
func (m *CMsgSOCacheSubscriptionCheck) String() string            { return proto.CompactTextString(m) }
func (*CMsgSOCacheSubscriptionCheck) ProtoMessage()               {}
func (*CMsgSOCacheSubscriptionCheck) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

func (m *CMsgSOCacheSubscriptionCheck) GetVersion() uint64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *CMsgSOCacheSubscriptionCheck) GetOwnerSoid() *CMsgSOIDOwner {
	if m != nil {
		return m.OwnerSoid
	}
	return nil
}

type CMsgSOCacheSubscriptionRefresh struct {
	OwnerSoid        *CMsgSOIDOwner `protobuf:"bytes,2,opt,name=owner_soid" json:"owner_soid,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *CMsgSOCacheSubscriptionRefresh) Reset()                    { *m = CMsgSOCacheSubscriptionRefresh{} }
func (m *CMsgSOCacheSubscriptionRefresh) String() string            { return proto.CompactTextString(m) }
func (*CMsgSOCacheSubscriptionRefresh) ProtoMessage()               {}
func (*CMsgSOCacheSubscriptionRefresh) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{6} }

func (m *CMsgSOCacheSubscriptionRefresh) GetOwnerSoid() *CMsgSOIDOwner {
	if m != nil {
		return m.OwnerSoid
	}
	return nil
}

type CMsgSOCacheVersion struct {
	Version          *uint64 `protobuf:"fixed64,1,opt,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgSOCacheVersion) Reset()                    { *m = CMsgSOCacheVersion{} }
func (m *CMsgSOCacheVersion) String() string            { return proto.CompactTextString(m) }
func (*CMsgSOCacheVersion) ProtoMessage()               {}
func (*CMsgSOCacheVersion) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{7} }

func (m *CMsgSOCacheVersion) GetVersion() uint64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type CMsgAccountDetails struct {
	Valid                      *bool   `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	AccountName                *string `protobuf:"bytes,2,opt,name=account_name" json:"account_name,omitempty"`
	PublicProfile              *bool   `protobuf:"varint,4,opt,name=public_profile" json:"public_profile,omitempty"`
	PublicInventory            *bool   `protobuf:"varint,5,opt,name=public_inventory" json:"public_inventory,omitempty"`
	VacBanned                  *bool   `protobuf:"varint,6,opt,name=vac_banned" json:"vac_banned,omitempty"`
	CyberCafe                  *bool   `protobuf:"varint,7,opt,name=cyber_cafe" json:"cyber_cafe,omitempty"`
	SchoolAccount              *bool   `protobuf:"varint,8,opt,name=school_account" json:"school_account,omitempty"`
	FreeTrialAccount           *bool   `protobuf:"varint,9,opt,name=free_trial_account" json:"free_trial_account,omitempty"`
	Subscribed                 *bool   `protobuf:"varint,10,opt,name=subscribed" json:"subscribed,omitempty"`
	LowViolence                *bool   `protobuf:"varint,11,opt,name=low_violence" json:"low_violence,omitempty"`
	Limited                    *bool   `protobuf:"varint,12,opt,name=limited" json:"limited,omitempty"`
	Trusted                    *bool   `protobuf:"varint,13,opt,name=trusted" json:"trusted,omitempty"`
	Package                    *uint32 `protobuf:"varint,14,opt,name=package" json:"package,omitempty"`
	TimeCached                 *uint32 `protobuf:"fixed32,15,opt,name=time_cached" json:"time_cached,omitempty"`
	AccountLocked              *bool   `protobuf:"varint,16,opt,name=account_locked" json:"account_locked,omitempty"`
	CommunityBanned            *bool   `protobuf:"varint,17,opt,name=community_banned" json:"community_banned,omitempty"`
	TradeBanned                *bool   `protobuf:"varint,18,opt,name=trade_banned" json:"trade_banned,omitempty"`
	EligibleForCommunityMarket *bool   `protobuf:"varint,19,opt,name=eligible_for_community_market" json:"eligible_for_community_market,omitempty"`
	XXX_unrecognized           []byte  `json:"-"`
}

func (m *CMsgAccountDetails) Reset()                    { *m = CMsgAccountDetails{} }
func (m *CMsgAccountDetails) String() string            { return proto.CompactTextString(m) }
func (*CMsgAccountDetails) ProtoMessage()               {}
func (*CMsgAccountDetails) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{8} }

func (m *CMsgAccountDetails) GetValid() bool {
	if m != nil && m.Valid != nil {
		return *m.Valid
	}
	return false
}

func (m *CMsgAccountDetails) GetAccountName() string {
	if m != nil && m.AccountName != nil {
		return *m.AccountName
	}
	return ""
}

func (m *CMsgAccountDetails) GetPublicProfile() bool {
	if m != nil && m.PublicProfile != nil {
		return *m.PublicProfile
	}
	return false
}

func (m *CMsgAccountDetails) GetPublicInventory() bool {
	if m != nil && m.PublicInventory != nil {
		return *m.PublicInventory
	}
	return false
}

func (m *CMsgAccountDetails) GetVacBanned() bool {
	if m != nil && m.VacBanned != nil {
		return *m.VacBanned
	}
	return false
}

func (m *CMsgAccountDetails) GetCyberCafe() bool {
	if m != nil && m.CyberCafe != nil {
		return *m.CyberCafe
	}
	return false
}

func (m *CMsgAccountDetails) GetSchoolAccount() bool {
	if m != nil && m.SchoolAccount != nil {
		return *m.SchoolAccount
	}
	return false
}

func (m *CMsgAccountDetails) GetFreeTrialAccount() bool {
	if m != nil && m.FreeTrialAccount != nil {
		return *m.FreeTrialAccount
	}
	return false
}

func (m *CMsgAccountDetails) GetSubscribed() bool {
	if m != nil && m.Subscribed != nil {
		return *m.Subscribed
	}
	return false
}

func (m *CMsgAccountDetails) GetLowViolence() bool {
	if m != nil && m.LowViolence != nil {
		return *m.LowViolence
	}
	return false
}

func (m *CMsgAccountDetails) GetLimited() bool {
	if m != nil && m.Limited != nil {
		return *m.Limited
	}
	return false
}

func (m *CMsgAccountDetails) GetTrusted() bool {
	if m != nil && m.Trusted != nil {
		return *m.Trusted
	}
	return false
}

func (m *CMsgAccountDetails) GetPackage() uint32 {
	if m != nil && m.Package != nil {
		return *m.Package
	}
	return 0
}

func (m *CMsgAccountDetails) GetTimeCached() uint32 {
	if m != nil && m.TimeCached != nil {
		return *m.TimeCached
	}
	return 0
}

func (m *CMsgAccountDetails) GetAccountLocked() bool {
	if m != nil && m.AccountLocked != nil {
		return *m.AccountLocked
	}
	return false
}

func (m *CMsgAccountDetails) GetCommunityBanned() bool {
	if m != nil && m.CommunityBanned != nil {
		return *m.CommunityBanned
	}
	return false
}

func (m *CMsgAccountDetails) GetTradeBanned() bool {
	if m != nil && m.TradeBanned != nil {
		return *m.TradeBanned
	}
	return false
}

func (m *CMsgAccountDetails) GetEligibleForCommunityMarket() bool {
	if m != nil && m.EligibleForCommunityMarket != nil {
		return *m.EligibleForCommunityMarket
	}
	return false
}

type CMsgGCMultiplexMessage struct {
	Msgtype          *uint32  `protobuf:"varint,1,opt,name=msgtype" json:"msgtype,omitempty"`
	Payload          []byte   `protobuf:"bytes,2,opt,name=payload" json:"payload,omitempty"`
	Steamids         []uint64 `protobuf:"fixed64,3,rep,name=steamids" json:"steamids,omitempty"`
	Replytogc        *bool    `protobuf:"varint,4,opt,name=replytogc" json:"replytogc,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CMsgGCMultiplexMessage) Reset()                    { *m = CMsgGCMultiplexMessage{} }
func (m *CMsgGCMultiplexMessage) String() string            { return proto.CompactTextString(m) }
func (*CMsgGCMultiplexMessage) ProtoMessage()               {}
func (*CMsgGCMultiplexMessage) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{9} }

func (m *CMsgGCMultiplexMessage) GetMsgtype() uint32 {
	if m != nil && m.Msgtype != nil {
		return *m.Msgtype
	}
	return 0
}

func (m *CMsgGCMultiplexMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *CMsgGCMultiplexMessage) GetSteamids() []uint64 {
	if m != nil {
		return m.Steamids
	}
	return nil
}

func (m *CMsgGCMultiplexMessage) GetReplytogc() bool {
	if m != nil && m.Replytogc != nil {
		return *m.Replytogc
	}
	return false
}

type CMsgGCMultiplexMessage_Response struct {
	Msgtype          *uint32 `protobuf:"varint,1,opt,name=msgtype" json:"msgtype,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgGCMultiplexMessage_Response) Reset()         { *m = CMsgGCMultiplexMessage_Response{} }
func (m *CMsgGCMultiplexMessage_Response) String() string { return proto.CompactTextString(m) }
func (*CMsgGCMultiplexMessage_Response) ProtoMessage()    {}
func (*CMsgGCMultiplexMessage_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{10}
}

func (m *CMsgGCMultiplexMessage_Response) GetMsgtype() uint32 {
	if m != nil && m.Msgtype != nil {
		return *m.Msgtype
	}
	return 0
}

type CGCToGCMsgMasterAck struct {
	DirIndex         *uint32 `protobuf:"varint,1,opt,name=dir_index" json:"dir_index,omitempty"`
	GcType           *uint32 `protobuf:"varint,2,opt,name=gc_type" json:"gc_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CGCToGCMsgMasterAck) Reset()                    { *m = CGCToGCMsgMasterAck{} }
func (m *CGCToGCMsgMasterAck) String() string            { return proto.CompactTextString(m) }
func (*CGCToGCMsgMasterAck) ProtoMessage()               {}
func (*CGCToGCMsgMasterAck) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{11} }

func (m *CGCToGCMsgMasterAck) GetDirIndex() uint32 {
	if m != nil && m.DirIndex != nil {
		return *m.DirIndex
	}
	return 0
}

func (m *CGCToGCMsgMasterAck) GetGcType() uint32 {
	if m != nil && m.GcType != nil {
		return *m.GcType
	}
	return 0
}

type CGCToGCMsgMasterAck_Response struct {
	Eresult          *int32 `protobuf:"varint,1,opt,name=eresult,def=2" json:"eresult,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CGCToGCMsgMasterAck_Response) Reset()                    { *m = CGCToGCMsgMasterAck_Response{} }
func (m *CGCToGCMsgMasterAck_Response) String() string            { return proto.CompactTextString(m) }
func (*CGCToGCMsgMasterAck_Response) ProtoMessage()               {}
func (*CGCToGCMsgMasterAck_Response) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{12} }

const Default_CGCToGCMsgMasterAck_Response_Eresult int32 = 2

func (m *CGCToGCMsgMasterAck_Response) GetEresult() int32 {
	if m != nil && m.Eresult != nil {
		return *m.Eresult
	}
	return Default_CGCToGCMsgMasterAck_Response_Eresult
}

type CGCToGCMsgMasterStartupComplete struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CGCToGCMsgMasterStartupComplete) Reset()         { *m = CGCToGCMsgMasterStartupComplete{} }
func (m *CGCToGCMsgMasterStartupComplete) String() string { return proto.CompactTextString(m) }
func (*CGCToGCMsgMasterStartupComplete) ProtoMessage()    {}
func (*CGCToGCMsgMasterStartupComplete) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{13}
}

type CGCToGCMsgRouted struct {
	MsgType          *uint32 `protobuf:"varint,1,opt,name=msg_type" json:"msg_type,omitempty"`
	SenderId         *uint64 `protobuf:"fixed64,2,opt,name=sender_id" json:"sender_id,omitempty"`
	NetMessage       []byte  `protobuf:"bytes,3,opt,name=net_message" json:"net_message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CGCToGCMsgRouted) Reset()                    { *m = CGCToGCMsgRouted{} }
func (m *CGCToGCMsgRouted) String() string            { return proto.CompactTextString(m) }
func (*CGCToGCMsgRouted) ProtoMessage()               {}
func (*CGCToGCMsgRouted) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{14} }

func (m *CGCToGCMsgRouted) GetMsgType() uint32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *CGCToGCMsgRouted) GetSenderId() uint64 {
	if m != nil && m.SenderId != nil {
		return *m.SenderId
	}
	return 0
}

func (m *CGCToGCMsgRouted) GetNetMessage() []byte {
	if m != nil {
		return m.NetMessage
	}
	return nil
}

type CGCToGCMsgRoutedReply struct {
	MsgType          *uint32 `protobuf:"varint,1,opt,name=msg_type" json:"msg_type,omitempty"`
	NetMessage       []byte  `protobuf:"bytes,2,opt,name=net_message" json:"net_message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CGCToGCMsgRoutedReply) Reset()                    { *m = CGCToGCMsgRoutedReply{} }
func (m *CGCToGCMsgRoutedReply) String() string            { return proto.CompactTextString(m) }
func (*CGCToGCMsgRoutedReply) ProtoMessage()               {}
func (*CGCToGCMsgRoutedReply) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{15} }

func (m *CGCToGCMsgRoutedReply) GetMsgType() uint32 {
	if m != nil && m.MsgType != nil {
		return *m.MsgType
	}
	return 0
}

func (m *CGCToGCMsgRoutedReply) GetNetMessage() []byte {
	if m != nil {
		return m.NetMessage
	}
	return nil
}

type CMsgGCUpdateSessionIP struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	Ip               *uint32 `protobuf:"fixed32,2,opt,name=ip" json:"ip,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgGCUpdateSessionIP) Reset()                    { *m = CMsgGCUpdateSessionIP{} }
func (m *CMsgGCUpdateSessionIP) String() string            { return proto.CompactTextString(m) }
func (*CMsgGCUpdateSessionIP) ProtoMessage()               {}
func (*CMsgGCUpdateSessionIP) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{16} }

func (m *CMsgGCUpdateSessionIP) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CMsgGCUpdateSessionIP) GetIp() uint32 {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return 0
}

type CMsgGCRequestSessionIP struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgGCRequestSessionIP) Reset()                    { *m = CMsgGCRequestSessionIP{} }
func (m *CMsgGCRequestSessionIP) String() string            { return proto.CompactTextString(m) }
func (*CMsgGCRequestSessionIP) ProtoMessage()               {}
func (*CMsgGCRequestSessionIP) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{17} }

func (m *CMsgGCRequestSessionIP) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

type CMsgGCRequestSessionIPResponse struct {
	Ip               *uint32 `protobuf:"fixed32,1,opt,name=ip" json:"ip,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CMsgGCRequestSessionIPResponse) Reset()                    { *m = CMsgGCRequestSessionIPResponse{} }
func (m *CMsgGCRequestSessionIPResponse) String() string            { return proto.CompactTextString(m) }
func (*CMsgGCRequestSessionIPResponse) ProtoMessage()               {}
func (*CMsgGCRequestSessionIPResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{18} }

func (m *CMsgGCRequestSessionIPResponse) GetIp() uint32 {
	if m != nil && m.Ip != nil {
		return *m.Ip
	}
	return 0
}

type CMsgSOCacheHaveVersion struct {
	Soid             *CMsgSOIDOwner `protobuf:"bytes,1,opt,name=soid" json:"soid,omitempty"`
	Version          *uint64        `protobuf:"fixed64,2,opt,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *CMsgSOCacheHaveVersion) Reset()                    { *m = CMsgSOCacheHaveVersion{} }
func (m *CMsgSOCacheHaveVersion) String() string            { return proto.CompactTextString(m) }
func (*CMsgSOCacheHaveVersion) ProtoMessage()               {}
func (*CMsgSOCacheHaveVersion) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{19} }

func (m *CMsgSOCacheHaveVersion) GetSoid() *CMsgSOIDOwner {
	if m != nil {
		return m.Soid
	}
	return nil
}

func (m *CMsgSOCacheHaveVersion) GetVersion() uint64 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

type CMsgClientHello struct {
	Version             *uint32                   `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	SocacheHaveVersions []*CMsgSOCacheHaveVersion `protobuf:"bytes,2,rep,name=socache_have_versions" json:"socache_have_versions,omitempty"`
	ClientSessionNeed   *uint32                   `protobuf:"varint,3,opt,name=client_session_need" json:"client_session_need,omitempty"`
	ClientLauncher      *uint32                   `protobuf:"varint,4,opt,name=client_launcher" json:"client_launcher,omitempty"`
	XXX_unrecognized    []byte                    `json:"-"`
}

func (m *CMsgClientHello) Reset()                    { *m = CMsgClientHello{} }
func (m *CMsgClientHello) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientHello) ProtoMessage()               {}
func (*CMsgClientHello) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{20} }

func (m *CMsgClientHello) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *CMsgClientHello) GetSocacheHaveVersions() []*CMsgSOCacheHaveVersion {
	if m != nil {
		return m.SocacheHaveVersions
	}
	return nil
}

func (m *CMsgClientHello) GetClientSessionNeed() uint32 {
	if m != nil && m.ClientSessionNeed != nil {
		return *m.ClientSessionNeed
	}
	return 0
}

func (m *CMsgClientHello) GetClientLauncher() uint32 {
	if m != nil && m.ClientLauncher != nil {
		return *m.ClientLauncher
	}
	return 0
}

type CMsgClientWelcome struct {
	Version                   *uint32                         `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	GameData                  []byte                          `protobuf:"bytes,2,opt,name=game_data" json:"game_data,omitempty"`
	OutofdateSubscribedCaches []*CMsgSOCacheSubscribed        `protobuf:"bytes,3,rep,name=outofdate_subscribed_caches" json:"outofdate_subscribed_caches,omitempty"`
	UptodateSubscribedCaches  []*CMsgSOCacheSubscriptionCheck `protobuf:"bytes,4,rep,name=uptodate_subscribed_caches" json:"uptodate_subscribed_caches,omitempty"`
	Location                  *CMsgClientWelcome_Location     `protobuf:"bytes,5,opt,name=location" json:"location,omitempty"`
	GameData2                 []byte                          `protobuf:"bytes,6,opt,name=game_data2" json:"game_data2,omitempty"`
	Rtime32GcWelcomeTimestamp *uint32                         `protobuf:"varint,7,opt,name=rtime32_gc_welcome_timestamp" json:"rtime32_gc_welcome_timestamp,omitempty"`
	Currency                  *uint32                         `protobuf:"varint,8,opt,name=currency" json:"currency,omitempty"`
	XXX_unrecognized          []byte                          `json:"-"`
}

func (m *CMsgClientWelcome) Reset()                    { *m = CMsgClientWelcome{} }
func (m *CMsgClientWelcome) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientWelcome) ProtoMessage()               {}
func (*CMsgClientWelcome) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{21} }

func (m *CMsgClientWelcome) GetVersion() uint32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *CMsgClientWelcome) GetGameData() []byte {
	if m != nil {
		return m.GameData
	}
	return nil
}

func (m *CMsgClientWelcome) GetOutofdateSubscribedCaches() []*CMsgSOCacheSubscribed {
	if m != nil {
		return m.OutofdateSubscribedCaches
	}
	return nil
}

func (m *CMsgClientWelcome) GetUptodateSubscribedCaches() []*CMsgSOCacheSubscriptionCheck {
	if m != nil {
		return m.UptodateSubscribedCaches
	}
	return nil
}

func (m *CMsgClientWelcome) GetLocation() *CMsgClientWelcome_Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *CMsgClientWelcome) GetGameData2() []byte {
	if m != nil {
		return m.GameData2
	}
	return nil
}

func (m *CMsgClientWelcome) GetRtime32GcWelcomeTimestamp() uint32 {
	if m != nil && m.Rtime32GcWelcomeTimestamp != nil {
		return *m.Rtime32GcWelcomeTimestamp
	}
	return 0
}

func (m *CMsgClientWelcome) GetCurrency() uint32 {
	if m != nil && m.Currency != nil {
		return *m.Currency
	}
	return 0
}

type CMsgClientWelcome_Location struct {
	Latitude         *float32 `protobuf:"fixed32,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude        *float32 `protobuf:"fixed32,2,opt,name=longitude" json:"longitude,omitempty"`
	Country          *string  `protobuf:"bytes,3,opt,name=country" json:"country,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CMsgClientWelcome_Location) Reset()                    { *m = CMsgClientWelcome_Location{} }
func (m *CMsgClientWelcome_Location) String() string            { return proto.CompactTextString(m) }
func (*CMsgClientWelcome_Location) ProtoMessage()               {}
func (*CMsgClientWelcome_Location) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{21, 0} }

func (m *CMsgClientWelcome_Location) GetLatitude() float32 {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return 0
}

func (m *CMsgClientWelcome_Location) GetLongitude() float32 {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return 0
}

func (m *CMsgClientWelcome_Location) GetCountry() string {
	if m != nil && m.Country != nil {
		return *m.Country
	}
	return ""
}

type CMsgConnectionStatus struct {
	Status                        *GCConnectionStatus `protobuf:"varint,1,opt,name=status,enum=GCConnectionStatus,def=0" json:"status,omitempty"`
	ClientSessionNeed             *uint32             `protobuf:"varint,2,opt,name=client_session_need" json:"client_session_need,omitempty"`
	QueuePosition                 *int32              `protobuf:"varint,3,opt,name=queue_position" json:"queue_position,omitempty"`
	QueueSize                     *int32              `protobuf:"varint,4,opt,name=queue_size" json:"queue_size,omitempty"`
	WaitSeconds                   *int32              `protobuf:"varint,5,opt,name=wait_seconds" json:"wait_seconds,omitempty"`
	EstimatedWaitSecondsRemaining *int32              `protobuf:"varint,6,opt,name=estimated_wait_seconds_remaining" json:"estimated_wait_seconds_remaining,omitempty"`
	XXX_unrecognized              []byte              `json:"-"`
}

func (m *CMsgConnectionStatus) Reset()                    { *m = CMsgConnectionStatus{} }
func (m *CMsgConnectionStatus) String() string            { return proto.CompactTextString(m) }
func (*CMsgConnectionStatus) ProtoMessage()               {}
func (*CMsgConnectionStatus) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{22} }

const Default_CMsgConnectionStatus_Status GCConnectionStatus = GCConnectionStatus_GCConnectionStatus_HAVE_SESSION

func (m *CMsgConnectionStatus) GetStatus() GCConnectionStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Default_CMsgConnectionStatus_Status
}

func (m *CMsgConnectionStatus) GetClientSessionNeed() uint32 {
	if m != nil && m.ClientSessionNeed != nil {
		return *m.ClientSessionNeed
	}
	return 0
}

func (m *CMsgConnectionStatus) GetQueuePosition() int32 {
	if m != nil && m.QueuePosition != nil {
		return *m.QueuePosition
	}
	return 0
}

func (m *CMsgConnectionStatus) GetQueueSize() int32 {
	if m != nil && m.QueueSize != nil {
		return *m.QueueSize
	}
	return 0
}

func (m *CMsgConnectionStatus) GetWaitSeconds() int32 {
	if m != nil && m.WaitSeconds != nil {
		return *m.WaitSeconds
	}
	return 0
}

func (m *CMsgConnectionStatus) GetEstimatedWaitSecondsRemaining() int32 {
	if m != nil && m.EstimatedWaitSecondsRemaining != nil {
		return *m.EstimatedWaitSecondsRemaining
	}
	return 0
}

type CWorkshop_PopulateItemDescriptions_Request struct {
	Appid            *uint32                                                                     `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	Languages        []*CWorkshop_PopulateItemDescriptions_Request_ItemDescriptionsLanguageBlock `protobuf:"bytes,2,rep,name=languages" json:"languages,omitempty"`
	XXX_unrecognized []byte                                                                      `json:"-"`
}

func (m *CWorkshop_PopulateItemDescriptions_Request) Reset() {
	*m = CWorkshop_PopulateItemDescriptions_Request{}
}
func (m *CWorkshop_PopulateItemDescriptions_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CWorkshop_PopulateItemDescriptions_Request) ProtoMessage() {}
func (*CWorkshop_PopulateItemDescriptions_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{23}
}

func (m *CWorkshop_PopulateItemDescriptions_Request) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CWorkshop_PopulateItemDescriptions_Request) GetLanguages() []*CWorkshop_PopulateItemDescriptions_Request_ItemDescriptionsLanguageBlock {
	if m != nil {
		return m.Languages
	}
	return nil
}

type CWorkshop_PopulateItemDescriptions_Request_SingleItemDescription struct {
	Gameitemid       *uint32 `protobuf:"varint,1,opt,name=gameitemid" json:"gameitemid,omitempty"`
	ItemDescription  *string `protobuf:"bytes,2,opt,name=item_description" json:"item_description,omitempty"`
	OnePerAccount    *bool   `protobuf:"varint,3,opt,name=one_per_account" json:"one_per_account,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CWorkshop_PopulateItemDescriptions_Request_SingleItemDescription) Reset() {
	*m = CWorkshop_PopulateItemDescriptions_Request_SingleItemDescription{}
}
func (m *CWorkshop_PopulateItemDescriptions_Request_SingleItemDescription) String() string {
	return proto.CompactTextString(m)
}
func (*CWorkshop_PopulateItemDescriptions_Request_SingleItemDescription) ProtoMessage() {}
func (*CWorkshop_PopulateItemDescriptions_Request_SingleItemDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{23, 0}
}

func (m *CWorkshop_PopulateItemDescriptions_Request_SingleItemDescription) GetGameitemid() uint32 {
	if m != nil && m.Gameitemid != nil {
		return *m.Gameitemid
	}
	return 0
}

func (m *CWorkshop_PopulateItemDescriptions_Request_SingleItemDescription) GetItemDescription() string {
	if m != nil && m.ItemDescription != nil {
		return *m.ItemDescription
	}
	return ""
}

func (m *CWorkshop_PopulateItemDescriptions_Request_SingleItemDescription) GetOnePerAccount() bool {
	if m != nil && m.OnePerAccount != nil {
		return *m.OnePerAccount
	}
	return false
}

type CWorkshop_PopulateItemDescriptions_Request_ItemDescriptionsLanguageBlock struct {
	Language         *string                                                             `protobuf:"bytes,1,opt,name=language" json:"language,omitempty"`
	Descriptions     []*CWorkshop_PopulateItemDescriptions_Request_SingleItemDescription `protobuf:"bytes,2,rep,name=descriptions" json:"descriptions,omitempty"`
	XXX_unrecognized []byte                                                              `json:"-"`
}

func (m *CWorkshop_PopulateItemDescriptions_Request_ItemDescriptionsLanguageBlock) Reset() {
	*m = CWorkshop_PopulateItemDescriptions_Request_ItemDescriptionsLanguageBlock{}
}
func (m *CWorkshop_PopulateItemDescriptions_Request_ItemDescriptionsLanguageBlock) String() string {
	return proto.CompactTextString(m)
}
func (*CWorkshop_PopulateItemDescriptions_Request_ItemDescriptionsLanguageBlock) ProtoMessage() {}
func (*CWorkshop_PopulateItemDescriptions_Request_ItemDescriptionsLanguageBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{23, 1}
}

func (m *CWorkshop_PopulateItemDescriptions_Request_ItemDescriptionsLanguageBlock) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

func (m *CWorkshop_PopulateItemDescriptions_Request_ItemDescriptionsLanguageBlock) GetDescriptions() []*CWorkshop_PopulateItemDescriptions_Request_SingleItemDescription {
	if m != nil {
		return m.Descriptions
	}
	return nil
}

type CWorkshop_GetContributors_Request struct {
	Appid            *uint32 `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	Gameitemid       *uint32 `protobuf:"varint,2,opt,name=gameitemid" json:"gameitemid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CWorkshop_GetContributors_Request) Reset()         { *m = CWorkshop_GetContributors_Request{} }
func (m *CWorkshop_GetContributors_Request) String() string { return proto.CompactTextString(m) }
func (*CWorkshop_GetContributors_Request) ProtoMessage()    {}
func (*CWorkshop_GetContributors_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{24}
}

func (m *CWorkshop_GetContributors_Request) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CWorkshop_GetContributors_Request) GetGameitemid() uint32 {
	if m != nil && m.Gameitemid != nil {
		return *m.Gameitemid
	}
	return 0
}

type CWorkshop_GetContributors_Response struct {
	Contributors     []uint64 `protobuf:"fixed64,1,rep,name=contributors" json:"contributors,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CWorkshop_GetContributors_Response) Reset()         { *m = CWorkshop_GetContributors_Response{} }
func (m *CWorkshop_GetContributors_Response) String() string { return proto.CompactTextString(m) }
func (*CWorkshop_GetContributors_Response) ProtoMessage()    {}
func (*CWorkshop_GetContributors_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{25}
}

func (m *CWorkshop_GetContributors_Response) GetContributors() []uint64 {
	if m != nil {
		return m.Contributors
	}
	return nil
}

type CWorkshop_SetItemPaymentRules_Request struct {
	Appid                   *uint32                                                          `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	Gameitemid              *uint32                                                          `protobuf:"varint,2,opt,name=gameitemid" json:"gameitemid,omitempty"`
	AssociatedWorkshopFiles []*CWorkshop_SetItemPaymentRules_Request_WorkshopItemPaymentRule `protobuf:"bytes,3,rep,name=associated_workshop_files" json:"associated_workshop_files,omitempty"`
	PartnerAccounts         []*CWorkshop_SetItemPaymentRules_Request_PartnerItemPaymentRule  `protobuf:"bytes,4,rep,name=partner_accounts" json:"partner_accounts,omitempty"`
	XXX_unrecognized        []byte                                                           `json:"-"`
}

func (m *CWorkshop_SetItemPaymentRules_Request) Reset()         { *m = CWorkshop_SetItemPaymentRules_Request{} }
func (m *CWorkshop_SetItemPaymentRules_Request) String() string { return proto.CompactTextString(m) }
func (*CWorkshop_SetItemPaymentRules_Request) ProtoMessage()    {}
func (*CWorkshop_SetItemPaymentRules_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{26}
}

func (m *CWorkshop_SetItemPaymentRules_Request) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CWorkshop_SetItemPaymentRules_Request) GetGameitemid() uint32 {
	if m != nil && m.Gameitemid != nil {
		return *m.Gameitemid
	}
	return 0
}

func (m *CWorkshop_SetItemPaymentRules_Request) GetAssociatedWorkshopFiles() []*CWorkshop_SetItemPaymentRules_Request_WorkshopItemPaymentRule {
	if m != nil {
		return m.AssociatedWorkshopFiles
	}
	return nil
}

func (m *CWorkshop_SetItemPaymentRules_Request) GetPartnerAccounts() []*CWorkshop_SetItemPaymentRules_Request_PartnerItemPaymentRule {
	if m != nil {
		return m.PartnerAccounts
	}
	return nil
}

type CWorkshop_SetItemPaymentRules_Request_WorkshopItemPaymentRule struct {
	WorkshopFileId    *uint64  `protobuf:"varint,1,opt,name=workshop_file_id" json:"workshop_file_id,omitempty"`
	RevenuePercentage *float32 `protobuf:"fixed32,2,opt,name=revenue_percentage" json:"revenue_percentage,omitempty"`
	RuleDescription   *string  `protobuf:"bytes,3,opt,name=rule_description" json:"rule_description,omitempty"`
	XXX_unrecognized  []byte   `json:"-"`
}

func (m *CWorkshop_SetItemPaymentRules_Request_WorkshopItemPaymentRule) Reset() {
	*m = CWorkshop_SetItemPaymentRules_Request_WorkshopItemPaymentRule{}
}
func (m *CWorkshop_SetItemPaymentRules_Request_WorkshopItemPaymentRule) String() string {
	return proto.CompactTextString(m)
}
func (*CWorkshop_SetItemPaymentRules_Request_WorkshopItemPaymentRule) ProtoMessage() {}
func (*CWorkshop_SetItemPaymentRules_Request_WorkshopItemPaymentRule) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{26, 0}
}

func (m *CWorkshop_SetItemPaymentRules_Request_WorkshopItemPaymentRule) GetWorkshopFileId() uint64 {
	if m != nil && m.WorkshopFileId != nil {
		return *m.WorkshopFileId
	}
	return 0
}

func (m *CWorkshop_SetItemPaymentRules_Request_WorkshopItemPaymentRule) GetRevenuePercentage() float32 {
	if m != nil && m.RevenuePercentage != nil {
		return *m.RevenuePercentage
	}
	return 0
}

func (m *CWorkshop_SetItemPaymentRules_Request_WorkshopItemPaymentRule) GetRuleDescription() string {
	if m != nil && m.RuleDescription != nil {
		return *m.RuleDescription
	}
	return ""
}

type CWorkshop_SetItemPaymentRules_Request_PartnerItemPaymentRule struct {
	AccountId         *uint32  `protobuf:"varint,1,opt,name=account_id" json:"account_id,omitempty"`
	RevenuePercentage *float32 `protobuf:"fixed32,2,opt,name=revenue_percentage" json:"revenue_percentage,omitempty"`
	RuleDescription   *string  `protobuf:"bytes,3,opt,name=rule_description" json:"rule_description,omitempty"`
	XXX_unrecognized  []byte   `json:"-"`
}

func (m *CWorkshop_SetItemPaymentRules_Request_PartnerItemPaymentRule) Reset() {
	*m = CWorkshop_SetItemPaymentRules_Request_PartnerItemPaymentRule{}
}
func (m *CWorkshop_SetItemPaymentRules_Request_PartnerItemPaymentRule) String() string {
	return proto.CompactTextString(m)
}
func (*CWorkshop_SetItemPaymentRules_Request_PartnerItemPaymentRule) ProtoMessage() {}
func (*CWorkshop_SetItemPaymentRules_Request_PartnerItemPaymentRule) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{26, 1}
}

func (m *CWorkshop_SetItemPaymentRules_Request_PartnerItemPaymentRule) GetAccountId() uint32 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *CWorkshop_SetItemPaymentRules_Request_PartnerItemPaymentRule) GetRevenuePercentage() float32 {
	if m != nil && m.RevenuePercentage != nil {
		return *m.RevenuePercentage
	}
	return 0
}

func (m *CWorkshop_SetItemPaymentRules_Request_PartnerItemPaymentRule) GetRuleDescription() string {
	if m != nil && m.RuleDescription != nil {
		return *m.RuleDescription
	}
	return ""
}

type CWorkshop_SetItemPaymentRules_Response struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CWorkshop_SetItemPaymentRules_Response) Reset() {
	*m = CWorkshop_SetItemPaymentRules_Response{}
}
func (m *CWorkshop_SetItemPaymentRules_Response) String() string { return proto.CompactTextString(m) }
func (*CWorkshop_SetItemPaymentRules_Response) ProtoMessage()    {}
func (*CWorkshop_SetItemPaymentRules_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{27}
}

func init() {
	proto.RegisterType((*CMsgSOIDOwner)(nil), "CMsgSOIDOwner")
	proto.RegisterType((*CMsgSOSingleObject)(nil), "CMsgSOSingleObject")
	proto.RegisterType((*CMsgSOMultipleObjects)(nil), "CMsgSOMultipleObjects")
	proto.RegisterType((*CMsgSOMultipleObjects_SingleObject)(nil), "CMsgSOMultipleObjects.SingleObject")
	proto.RegisterType((*CMsgSOCacheSubscribed)(nil), "CMsgSOCacheSubscribed")
	proto.RegisterType((*CMsgSOCacheSubscribed_SubscribedType)(nil), "CMsgSOCacheSubscribed.SubscribedType")
	proto.RegisterType((*CMsgSOCacheUnsubscribed)(nil), "CMsgSOCacheUnsubscribed")
	proto.RegisterType((*CMsgSOCacheSubscriptionCheck)(nil), "CMsgSOCacheSubscriptionCheck")
	proto.RegisterType((*CMsgSOCacheSubscriptionRefresh)(nil), "CMsgSOCacheSubscriptionRefresh")
	proto.RegisterType((*CMsgSOCacheVersion)(nil), "CMsgSOCacheVersion")
	proto.RegisterType((*CMsgAccountDetails)(nil), "CMsgAccountDetails")
	proto.RegisterType((*CMsgGCMultiplexMessage)(nil), "CMsgGCMultiplexMessage")
	proto.RegisterType((*CMsgGCMultiplexMessage_Response)(nil), "CMsgGCMultiplexMessage_Response")
	proto.RegisterType((*CGCToGCMsgMasterAck)(nil), "CGCToGCMsgMasterAck")
	proto.RegisterType((*CGCToGCMsgMasterAck_Response)(nil), "CGCToGCMsgMasterAck_Response")
	proto.RegisterType((*CGCToGCMsgMasterStartupComplete)(nil), "CGCToGCMsgMasterStartupComplete")
	proto.RegisterType((*CGCToGCMsgRouted)(nil), "CGCToGCMsgRouted")
	proto.RegisterType((*CGCToGCMsgRoutedReply)(nil), "CGCToGCMsgRoutedReply")
	proto.RegisterType((*CMsgGCUpdateSessionIP)(nil), "CMsgGCUpdateSessionIP")
	proto.RegisterType((*CMsgGCRequestSessionIP)(nil), "CMsgGCRequestSessionIP")
	proto.RegisterType((*CMsgGCRequestSessionIPResponse)(nil), "CMsgGCRequestSessionIPResponse")
	proto.RegisterType((*CMsgSOCacheHaveVersion)(nil), "CMsgSOCacheHaveVersion")
	proto.RegisterType((*CMsgClientHello)(nil), "CMsgClientHello")
	proto.RegisterType((*CMsgClientWelcome)(nil), "CMsgClientWelcome")
	proto.RegisterType((*CMsgClientWelcome_Location)(nil), "CMsgClientWelcome.Location")
	proto.RegisterType((*CMsgConnectionStatus)(nil), "CMsgConnectionStatus")
	proto.RegisterType((*CWorkshop_PopulateItemDescriptions_Request)(nil), "CWorkshop_PopulateItemDescriptions_Request")
	proto.RegisterType((*CWorkshop_PopulateItemDescriptions_Request_SingleItemDescription)(nil), "CWorkshop_PopulateItemDescriptions_Request.SingleItemDescription")
	proto.RegisterType((*CWorkshop_PopulateItemDescriptions_Request_ItemDescriptionsLanguageBlock)(nil), "CWorkshop_PopulateItemDescriptions_Request.ItemDescriptionsLanguageBlock")
	proto.RegisterType((*CWorkshop_GetContributors_Request)(nil), "CWorkshop_GetContributors_Request")
	proto.RegisterType((*CWorkshop_GetContributors_Response)(nil), "CWorkshop_GetContributors_Response")
	proto.RegisterType((*CWorkshop_SetItemPaymentRules_Request)(nil), "CWorkshop_SetItemPaymentRules_Request")
	proto.RegisterType((*CWorkshop_SetItemPaymentRules_Request_WorkshopItemPaymentRule)(nil), "CWorkshop_SetItemPaymentRules_Request.WorkshopItemPaymentRule")
	proto.RegisterType((*CWorkshop_SetItemPaymentRules_Request_PartnerItemPaymentRule)(nil), "CWorkshop_SetItemPaymentRules_Request.PartnerItemPaymentRule")
	proto.RegisterType((*CWorkshop_SetItemPaymentRules_Response)(nil), "CWorkshop_SetItemPaymentRules_Response")
	proto.RegisterEnum("GCConnectionStatus", GCConnectionStatus_name, GCConnectionStatus_value)
}

var fileDescriptor4 = []byte{
	// 1626 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x56, 0xdd, 0x4e, 0x1b, 0xdb,
	0x15, 0x8e, 0x7f, 0x00, 0xb3, 0xb0, 0xc1, 0x19, 0x12, 0x70, 0x4d, 0x68, 0x92, 0x49, 0xa9, 0x68,
	0x94, 0x5a, 0x95, 0x5b, 0x45, 0x2a, 0x6d, 0xa2, 0x12, 0x43, 0x0d, 0x12, 0x60, 0x8a, 0x43, 0x90,
	0xaa, 0xaa, 0x5b, 0xe3, 0xf1, 0xc6, 0x4c, 0x99, 0x99, 0x3d, 0x9d, 0xbd, 0x07, 0xe2, 0x5e, 0xe5,
	0xaa, 0xaa, 0x7a, 0xd5, 0xa7, 0xa8, 0xce, 0x43, 0x9c, 0xfb, 0xf3, 0x04, 0x79, 0x84, 0xf3, 0x06,
	0xe7, 0x01, 0xce, 0xda, 0x7b, 0xcf, 0xf8, 0x77, 0x4c, 0xc8, 0xb9, 0x41, 0x66, 0xcd, 0xfa, 0xfd,
	0xd6, 0x5a, 0xdf, 0xda, 0xb0, 0xd6, 0xb3, 0x79, 0xf7, 0x9a, 0xf4, 0x6c, 0x8f, 0x72, 0x6e, 0xf5,
	0x28, 0xaf, 0x05, 0x21, 0x13, 0xac, 0xba, 0xca, 0x05, 0xb5, 0xbc, 0x71, 0xa1, 0xf9, 0x2b, 0x28,
	0x35, 0x8e, 0x79, 0xaf, 0xdd, 0x3a, 0xdc, 0x6b, 0xdd, 0xfa, 0x34, 0x34, 0x8a, 0x90, 0x17, 0xfd,
	0x80, 0x56, 0x32, 0xcf, 0x32, 0xdb, 0x25, 0x03, 0x20, 0xeb, 0x74, 0x2b, 0x59, 0xfc, 0x9d, 0x37,
	0x19, 0x18, 0x5a, 0xb5, 0xed, 0xf8, 0x3d, 0x97, 0xb6, 0x3a, 0xff, 0xa0, 0xb6, 0x30, 0x56, 0x60,
	0x41, 0xea, 0x93, 0x58, 0x6d, 0xce, 0x58, 0x85, 0x25, 0xa6, 0x3e, 0x91, 0xae, 0x25, 0xac, 0x4a,
	0x0e, 0x85, 0x45, 0xa9, 0x75, 0x43, 0x43, 0xee, 0x30, 0xbf, 0x92, 0x47, 0xc1, 0xbc, 0x61, 0x02,
	0x30, 0x19, 0x8f, 0x70, 0x86, 0x96, 0x73, 0x28, 0x5b, 0xaa, 0x2f, 0xd7, 0xc6, 0x52, 0x31, 0xbf,
	0xcb, 0xc2, 0x63, 0x2d, 0x39, 0x8e, 0x5c, 0xe1, 0x04, 0x49, 0x4c, 0x6e, 0xbc, 0x81, 0xb2, 0x8e,
	0xc1, 0x89, 0xc7, 0xba, 0xce, 0xa5, 0x43, 0x65, 0xf4, 0x1c, 0xfa, 0x78, 0x51, 0x4b, 0xb5, 0xa8,
	0x4d, 0xe6, 0x9c, 0x64, 0x93, 0x53, 0xd9, 0xec, 0x40, 0x29, 0xf1, 0x67, 0x75, 0xbb, 0xe8, 0x2c,
	0x7f, 0x7f, 0x67, 0x7f, 0x84, 0x95, 0xc4, 0x36, 0xa4, 0x1e, 0xbb, 0xa1, 0xb2, 0x9c, 0x7b, 0x5b,
	0x8f, 0xe3, 0x30, 0x9f, 0x86, 0x43, 0xf5, 0x4f, 0x50, 0x9c, 0x05, 0x79, 0x26, 0x0d, 0x72, 0xd9,
	0x87, 0xe2, 0x0e, 0x7c, 0xfa, 0xff, 0xe6, 0xa7, 0xec, 0x7f, 0xf0, 0x4f, 0xc1, 0xfc, 0x36, 0x93,
	0x20, 0xd9, 0xb0, 0xec, 0x2b, 0xda, 0x8e, 0x3a, 0xdc, 0x0e, 0x9d, 0x0e, 0xed, 0x1a, 0xaf, 0x61,
	0x21, 0xce, 0x3e, 0x06, 0x70, 0xab, 0x96, 0xaa, 0x58, 0x1b, 0xfe, 0x7c, 0x8f, 0xb1, 0xa7, 0x21,
	0x1c, 0x2f, 0x24, 0x9f, 0x5a, 0xc8, 0x6b, 0x58, 0x9e, 0x76, 0xf3, 0x85, 0x52, 0x72, 0xdb, 0x45,
	0xf3, 0x0d, 0xac, 0x8f, 0x24, 0x75, 0xee, 0xf3, 0x61, 0xfe, 0xe3, 0x61, 0xb3, 0xa9, 0x73, 0xd4,
	0x86, 0x27, 0xd3, 0x35, 0x05, 0x02, 0x73, 0x6f, 0x5c, 0x51, 0xfb, 0x7a, 0xb4, 0x96, 0x6c, 0x4a,
	0x2d, 0xb9, 0x54, 0xa7, 0x7b, 0xf0, 0xf3, 0x19, 0x4e, 0xcf, 0xe8, 0x65, 0x48, 0xf9, 0xd5, 0xbd,
	0x52, 0xdb, 0x4a, 0x76, 0x4a, 0x79, 0xf9, 0xa0, 0xb3, 0x18, 0x4d, 0x48, 0xa2, 0x32, 0x6f, 0x7e,
	0x93, 0xd3, 0x7a, 0xbb, 0xb6, 0xcd, 0x22, 0x5f, 0xec, 0x51, 0x61, 0x39, 0x2e, 0x37, 0x4a, 0x30,
	0x77, 0x63, 0xb9, 0x31, 0x76, 0x05, 0xe3, 0x11, 0x14, 0x2d, 0xad, 0x40, 0x7c, 0xcb, 0xa3, 0x2a,
	0xe4, 0xa2, 0xb1, 0x06, 0xcb, 0x41, 0xd4, 0x71, 0x1d, 0x9b, 0xe0, 0xc6, 0x5f, 0x3a, 0x2e, 0x55,
	0xcd, 0x29, 0x18, 0x15, 0x28, 0xc7, 0x72, 0xc7, 0xbf, 0xa1, 0xbe, 0x60, 0x61, 0x5f, 0xed, 0x61,
	0xc1, 0xc0, 0xad, 0xbf, 0xb1, 0x6c, 0xd2, 0xb1, 0x7c, 0x9f, 0xea, 0x99, 0x54, 0x32, 0xbb, 0xdf,
	0xc1, 0x62, 0x6c, 0xeb, 0x92, 0x56, 0x16, 0x94, 0x0c, 0x3d, 0x73, 0xfb, 0x8a, 0x31, 0x97, 0xc4,
	0x61, 0x2b, 0x05, 0x25, 0xaf, 0x82, 0x81, 0x08, 0x50, 0x22, 0x42, 0xc7, 0x1a, 0x7e, 0x5b, 0x4c,
	0xfc, 0x0c, 0xbb, 0x57, 0x81, 0x24, 0x6f, 0x97, 0xdd, 0x92, 0x1b, 0x87, 0xb9, 0xd4, 0xb7, 0x69,
	0x65, 0x49, 0x49, 0x11, 0x04, 0xd7, 0xf1, 0x1c, 0x81, 0x6a, 0xc5, 0x44, 0x20, 0xc2, 0x88, 0x4b,
	0x41, 0x29, 0x11, 0x04, 0x96, 0x7d, 0x8d, 0x6c, 0x56, 0x59, 0x56, 0x6c, 0x85, 0xc3, 0x23, 0x1c,
	0x8f, 0x62, 0x8e, 0x08, 0x66, 0xb7, 0xb2, 0x82, 0xc2, 0x05, 0x99, 0x65, 0x82, 0x8a, 0xcb, 0xec,
	0x6b, 0x94, 0x97, 0x93, 0xfa, 0x6d, 0xe6, 0x79, 0x91, 0xef, 0x88, 0x7e, 0x52, 0xeb, 0xc3, 0x24,
	0x1f, 0x11, 0x5a, 0x5d, 0x9a, 0x48, 0x0d, 0x25, 0xdd, 0x82, 0x4d, 0xea, 0x3a, 0x3d, 0xa7, 0xe3,
	0x52, 0x72, 0xc9, 0x10, 0x88, 0x81, 0xb1, 0x67, 0x85, 0xd7, 0x54, 0x54, 0x56, 0xa5, 0x9a, 0x49,
	0x60, 0x4d, 0x76, 0xaa, 0xd9, 0x48, 0xd6, 0xfe, 0xe3, 0xb1, 0x66, 0x5c, 0x99, 0xae, 0xc7, 0x7b,
	0x23, 0xe4, 0xaa, 0xf2, 0xef, 0xbb, 0xcc, 0xd2, 0xd3, 0x51, 0x34, 0xca, 0x50, 0x50, 0x1c, 0xed,
	0x74, 0x39, 0x4e, 0x5d, 0x0e, 0x27, 0xf1, 0x21, 0x2c, 0x86, 0x34, 0x70, 0xfb, 0x82, 0xf5, 0x6c,
	0xdd, 0x37, 0xb3, 0x0e, 0x4f, 0xd3, 0x03, 0x90, 0x33, 0xca, 0x03, 0xe6, 0xf3, 0xe9, 0x48, 0xe6,
	0xef, 0x61, 0xb5, 0xd1, 0x6c, 0xbc, 0x67, 0x4d, 0x69, 0x79, 0x6c, 0x61, 0x90, 0x70, 0x17, 0x07,
	0x1f, 0xbd, 0x77, 0x9d, 0x10, 0xfb, 0xdf, 0xa5, 0x1f, 0x87, 0x39, 0xf5, 0x6c, 0xa2, 0x4c, 0xb3,
	0xca, 0xb4, 0x8e, 0xcb, 0x33, 0x6d, 0x3a, 0x8c, 0x65, 0xc0, 0x02, 0xc5, 0x71, 0xc7, 0x5c, 0xf4,
	0x06, 0xef, 0x64, 0xea, 0xe6, 0x73, 0x4c, 0x71, 0xc2, 0xa6, 0x2d, 0xac, 0x50, 0x44, 0x41, 0x83,
	0x79, 0x98, 0xb1, 0xa0, 0xe6, 0x11, 0x94, 0x87, 0x2a, 0x67, 0x2c, 0xc2, 0xae, 0xca, 0xf2, 0x31,
	0x6d, 0x32, 0x82, 0x10, 0x26, 0xc8, 0x29, 0x66, 0x17, 0x26, 0xe7, 0x65, 0x5e, 0xf6, 0xd8, 0xa7,
	0x82, 0xc4, 0x67, 0x4c, 0x9f, 0x17, 0xf3, 0x2d, 0xd2, 0xdb, 0x84, 0xb7, 0x33, 0x09, 0x5b, 0x8a,
	0xcb, 0x09, 0x7b, 0x05, 0xbc, 0xf9, 0x3b, 0x4d, 0x8f, 0xcd, 0xc6, 0x79, 0x80, 0xb4, 0x43, 0xdb,
	0xf8, 0x11, 0x97, 0xef, 0xf0, 0x54, 0xc2, 0x11, 0x77, 0x44, 0x6f, 0xa2, 0x3a, 0x88, 0x81, 0xb2,
	0x5a, 0xc0, 0xdb, 0x19, 0xb7, 0xfa, 0x8c, 0xfe, 0x33, 0xa2, 0x5c, 0xcc, 0x36, 0x33, 0x5f, 0x69,
	0xb6, 0x98, 0x56, 0x1d, 0xe0, 0xa8, 0x1d, 0x67, 0x94, 0xe3, 0xa6, 0x76, 0x1c, 0xb3, 0xc2, 0x81,
	0x75, 0x33, 0x60, 0x86, 0x27, 0x90, 0x57, 0x6c, 0x92, 0x49, 0x63, 0x93, 0x29, 0x22, 0x33, 0xff,
	0x97, 0x81, 0x15, 0xa9, 0xd2, 0x70, 0x1d, 0xdc, 0xf0, 0x03, 0xea, 0xba, 0x6c, 0x92, 0x5c, 0x4a,
	0x78, 0x02, 0x1e, 0x73, 0xa6, 0x56, 0x86, 0x5c, 0x61, 0x28, 0x12, 0x7f, 0x4d, 0x0e, 0xc2, 0x7a,
	0x6d, 0x46, 0x2e, 0x1b, 0xb0, 0x6a, 0x2b, 0xbf, 0x84, 0xeb, 0x6a, 0x88, 0x4f, 0xa9, 0xa6, 0xcb,
	0x92, 0xb1, 0x0e, 0x2b, 0xf1, 0x47, 0xd7, 0x8a, 0x7c, 0xb4, 0x0c, 0xd5, 0xf8, 0x96, 0xcc, 0x1f,
	0xb2, 0xf0, 0x70, 0x98, 0xd2, 0x05, 0x75, 0x71, 0x8f, 0xe8, 0x74, 0x52, 0xd8, 0xf9, 0x1e, 0x72,
	0xd8, 0xc8, 0x41, 0x33, 0xfe, 0x00, 0x1b, 0xd8, 0x59, 0x76, 0x29, 0x3b, 0x44, 0x86, 0x24, 0xa2,
	0xb7, 0x5d, 0x2f, 0xcc, 0x52, 0x7d, 0x2d, 0xfd, 0x7c, 0x19, 0xbb, 0x50, 0x8d, 0x02, 0xc1, 0x66,
	0xd8, 0xea, 0x73, 0xbf, 0x59, 0xbb, 0xf3, 0x4c, 0xfc, 0x1a, 0x0a, 0x48, 0x20, 0x96, 0x14, 0xc4,
	0x0f, 0x96, 0x8d, 0xda, 0x54, 0x25, 0xb5, 0xa3, 0x58, 0x45, 0x32, 0xdd, 0xa0, 0x82, 0xba, 0x62,
	0xd1, 0xa2, 0xf1, 0x0b, 0x78, 0x12, 0x4a, 0x86, 0xfa, 0x6d, 0x1d, 0x9f, 0x67, 0xe4, 0x56, 0x9b,
	0x10, 0x29, 0xe1, 0xc2, 0xf2, 0x02, 0xc5, 0xab, 0x25, 0x39, 0xb4, 0x76, 0x14, 0x86, 0xc8, 0x85,
	0x7d, 0xc5, 0xa8, 0x25, 0x7c, 0x01, 0x14, 0x06, 0x7e, 0xf1, 0xab, 0x8b, 0xbf, 0x44, 0xd4, 0xd5,
	0x23, 0x9d, 0x95, 0x58, 0xb9, 0xcc, 0xef, 0x69, 0x51, 0x56, 0x89, 0x10, 0x4f, 0x45, 0x79, 0xc8,
	0xe9, 0xb2, 0x1f, 0x8b, 0xe6, 0xf7, 0x19, 0x78, 0xa4, 0x92, 0x65, 0x48, 0x69, 0xb6, 0x74, 0x84,
	0x1b, 0x29, 0x22, 0x6e, 0xec, 0xc1, 0x3c, 0x57, 0xbf, 0x94, 0xb3, 0xe5, 0xfa, 0x6a, 0xad, 0xd9,
	0x98, 0x54, 0xda, 0x79, 0x3a, 0x2d, 0x23, 0x07, 0xbb, 0x1f, 0xf6, 0x49, 0x7b, 0xbf, 0xdd, 0x3e,
	0x6c, 0x9d, 0xcc, 0x9a, 0x05, 0x45, 0x21, 0x92, 0x81, 0x71, 0xe8, 0x23, 0x4a, 0x02, 0xc6, 0x1d,
	0x91, 0x3c, 0x19, 0xe6, 0x24, 0x42, 0x5a, 0xce, 0x9d, 0x7f, 0xe9, 0xab, 0x34, 0x27, 0xb9, 0xf7,
	0xd6, 0x72, 0xa4, 0x1b, 0x9b, 0xf9, 0x48, 0x83, 0x73, 0x4a, 0xba, 0x0d, 0xcf, 0x10, 0x21, 0xc7,
	0xc3, 0xee, 0x75, 0xc9, 0xe8, 0x77, 0xf9, 0xe4, 0xb2, 0x1c, 0x1f, 0x5f, 0x47, 0x0a, 0xe1, 0x39,
	0xf3, 0xdf, 0x39, 0x78, 0xd9, 0xb8, 0x60, 0xe1, 0x35, 0xbf, 0x62, 0x01, 0x39, 0x65, 0x41, 0x84,
	0x60, 0xd1, 0x43, 0x41, 0xbd, 0x3d, 0x3a, 0xe8, 0x27, 0x27, 0xf1, 0x1a, 0xca, 0x0b, 0x6a, 0x05,
	0x41, 0xbc, 0x50, 0x25, 0xe3, 0x6f, 0x88, 0xa4, 0xe5, 0xf7, 0x22, 0xf9, 0x40, 0x8e, 0xc7, 0xff,
	0xb0, 0x76, 0x7f, 0x77, 0xb5, 0xc9, 0x0f, 0x47, 0xb1, 0xb3, 0x77, 0xf2, 0xf2, 0x54, 0xff, 0x0e,
	0x8f, 0xf5, 0x3b, 0x6e, 0x42, 0x2d, 0x19, 0x15, 0xbc, 0x75, 0xde, 0x20, 0x15, 0x3c, 0x4f, 0xf2,
	0x7f, 0xd2, 0x1d, 0xea, 0xc5, 0x07, 0x1d, 0x57, 0x8b, 0xf9, 0x08, 0x26, 0xb2, 0x62, 0x72, 0x5b,
	0x25, 0x9e, 0x85, 0xea, 0x7f, 0x33, 0xb0, 0x79, 0x67, 0x06, 0x7a, 0x76, 0xb4, 0x40, 0x85, 0x59,
	0x34, 0x2e, 0xa0, 0x38, 0x12, 0x21, 0x29, 0x7a, 0xf7, 0x6b, 0x8a, 0x4e, 0xad, 0xc9, 0xfc, 0x33,
	0x3c, 0x1f, 0xfa, 0x68, 0x52, 0x81, 0xf3, 0x83, 0xef, 0x81, 0x0e, 0x2e, 0x70, 0x38, 0x13, 0xfe,
	0x71, 0x1c, 0xf4, 0xfd, 0xd9, 0x01, 0xf3, 0x2e, 0x3f, 0x31, 0x7b, 0xe2, 0xd8, 0xd8, 0x23, 0x1f,
	0xd0, 0x1f, 0x5e, 0x4f, 0xf3, 0x73, 0x0e, 0xb6, 0x86, 0xc6, 0x6d, 0x2a, 0x64, 0x92, 0xa7, 0x56,
	0xdf, 0xc3, 0x41, 0x3d, 0x8b, 0x5c, 0xfa, 0x35, 0x89, 0x18, 0x16, 0xfc, 0xcc, 0xe2, 0x48, 0x94,
	0x8e, 0x1e, 0xc2, 0xc4, 0xab, 0x7c, 0x51, 0x25, 0xe4, 0xf3, 0xb6, 0x76, 0xaf, 0x68, 0xb5, 0x44,
	0x69, 0x42, 0x01, 0x9b, 0x51, 0x0e, 0xf0, 0x4c, 0xfa, 0xc3, 0xce, 0x26, 0xd4, 0xf4, 0xe6, 0x9e,
	0x9e, 0x4f, 0xb5, 0xf9, 0xc4, 0xf7, 0xaa, 0x03, 0xeb, 0xb3, 0x62, 0xe2, 0x9c, 0x8d, 0xd5, 0x92,
	0x3c, 0xc5, 0xf3, 0xf2, 0x19, 0x17, 0x52, 0x7c, 0x19, 0x46, 0x6a, 0xd6, 0x6c, 0x34, 0x48, 0x0e,
	0x66, 0x56, 0x5a, 0x85, 0x68, 0x3d, 0x36, 0x9d, 0x8a, 0x68, 0xaa, 0x1d, 0x58, 0x4b, 0x4f, 0x42,
	0x82, 0x9a, 0x3c, 0xc4, 0x06, 0x40, 0xff, 0xa4, 0x18, 0xe6, 0x36, 0xfc, 0xf2, 0x4b, 0x70, 0xe8,
	0xb9, 0x78, 0xf9, 0x39, 0x03, 0xc6, 0x34, 0x77, 0x19, 0x2f, 0xe0, 0x4b, 0x8c, 0x56, 0x7e, 0x80,
	0x64, 0xfd, 0x2c, 0x45, 0xa9, 0xd9, 0x20, 0xcd, 0xd6, 0xe1, 0x49, 0x93, 0xec, 0xb5, 0x2e, 0x4e,
	0xca, 0x19, 0xe3, 0x39, 0x6c, 0xa6, 0x68, 0x9d, 0xb4, 0x06, 0x8e, 0xb2, 0xc6, 0x6f, 0xe0, 0xd5,
	0x9d, 0x2a, 0xe4, 0xf0, 0x84, 0x1c, 0xb5, 0x9a, 0xf8, 0xe3, 0x2f, 0xe7, 0xfb, 0xe7, 0xfb, 0xe5,
	0x9c, 0xf1, 0x14, 0x36, 0x66, 0x58, 0xbc, 0xdf, 0xdf, 0x3d, 0x2e, 0xe7, 0xdf, 0xad, 0x1c, 0x64,
	0xfe, 0x5a, 0xb0, 0x79, 0x8f, 0x75, 0xa2, 0x4b, 0xfe, 0x29, 0xf3, 0xe0, 0xc7, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x31, 0xf4, 0xd9, 0x3b, 0xf5, 0x0f, 0x00, 0x00,
}
